version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-crud-nodeapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2epf14tnni2"
s3_prefix = "aws-sam-crud-nodeapi"
region = "us-east-2"
profile = "dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
